<?
if ($HTTP_HOST=="w3future.com"||$HTTP_HOST=="www.w3future.com")
{header ("Location: http://w3future.com/weblog/"); exit;}
?>
<HTML>
<HEAD>
<TITLE>W3Revolution</TITLE>
<LINK REL="SHORTCUT ICON" HREF="ieicon.ico">
<SCRIPT language="javascript">
<!--
if (top!=window) top.location=window.location;
//-->
</SCRIPT>
</HEAD>

<frameset rows="*" border="0" marginwidth="0" marginheight="0" frameborder="0" framespacing="0">
	<frame src="w3revolution/start.html" name="start" scrolling="AUTO" border="0" marginwidth="0" marginheight="0" frameborder="0" framespacing="0">
</frameset>

<body>
</body>
</html>
