<?
class resultSet {
	var $result;
	var $fieldtype;

	function resultSet($query) {
		$result = mysql_query($query) or die("invalid query");
		$this->result=$result;
		if ($result) $this->getColumns($result);
	}

	function getColumns($result) {
		for ($i=0;$i<mysql_num_fields($result);$i++)
			$this->fieldtype[mysql_field_name($result,$i)]=mysql_field_type($result,$i);
	}

	function val($col) {
		return $this->row[$col];
	}

	function findItem() {
		$this->row=mysql_fetch_array($this->result);
		if ($this->row) {
			return true;
		} else return false;
	}
}

mysql_connect ("localhost","w3future","VPpniePs");
mysql_select_db ("w3future_com");
$rs = new resultSet("SELECT * FROM rdf");
?>
<table border="1" cellpadding="2" cellspacing="0" style="border-collapse: collapse" bordercolor="#808080" width="100%">
	<tr>
<?
	while (list ($name, $ftype) = each ($rs->fieldtype)) {
		echo "\t\t<td bgcolor='#808080' height='19'><font color='White'><b>$name</b></font></td>\n";
	}
?>	</tr>
<?
while ($rs->findItem()) {
	echo "\t<tr>\n";
	reset ($rs->fieldtype);
	while (list ($name, $ftype) = each ($rs->fieldtype)) {
		echo "\t\t<td width='25%' height='19'><b> <font face='Comic Sans MS' size='2'>". $rs->row[$name] ."</b></td>\n";
	}
	echo "\t</tr>\n";
}
?>
</table>
